# CapStone-[semester] 

trigger:
  branches:
    include:
      - main
      - [team-1-branch]
      - [team-2-branch]
    exclude:
      - [team-1-branch]-*
      - [team-2-branch]-*

pool:
  vmImage: 'windows-latest' # Required for FileTransform@2 task

stages:
- stage: 'build_capstone'
  displayName: '1. Build BackEnd and FrontEnd packages'
  variables:
    - group: build

  jobs:
  - job: 'build_capstone_backend'
    displayName: '1.1. Build BackEnd'

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(buildBackEndSolution)'
        arguments: '--configuration $(buildBackEndConfiguration)'
        workingDirectory: $(Build.SourcesDirectory)/$(buildBackEnd)
      displayName: '1.1.1. Build: Build using Solution File'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(buildBackEndProjects)'
        arguments: '--configuration $(buildBackEndConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildBackEnd)'
        zipAfterPublish: true
        modifyOutputPath: false
      displayName: '1.1.2. Publish: Create Archive Package in Staging Directory'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(buildBackEnd)'
        artifact: '$(buildBackEnd)'
        publishLocation: 'pipeline'
      displayName: '1.1.3. Publish: Publish BackEnd Build as a Pipeline Artifact'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global dotnet-ef'
      displayName: '1.1.4. Setup: Install Entity Framework tool'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'ef'
        arguments: 'migrations script --idempotent --project $(Build.SourcesDirectory)\$(buildBackEnd)\Data\Data.csproj --context ApiDataContext --startup-project $(Build.SourcesDirectory)\$(buildBackEnd)\WebAPI\WebAPI.csproj --configuration $(buildBackEndConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildBackEnd)/todo-db-script.sql'
      displayName: '1.1.5. Build: Generate Database Script'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(buildBackEnd)/todo-db-script.sql'
        artifact: '$(buildDatabase)'
        publishLocation: 'pipeline'
      displayName: '1.1.6. Publish: Publish Database Script as a Pipeline Artifact'

  - job: 'build_capstone_frontend'
    displayName: '1.2. Build FrontEnd'

    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
      displayName: '1.2.1. Setup: Install Node.js'

    - script: |
        npm install --global @angular/cli
      workingDirectory: $(Build.SourcesDirectory)/$(buildFrontEnd)
      displayName: '1.2.2. Setup: Install Angular'

    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)/$(buildFrontEnd)
      displayName: '1.2.3. Setup: Install Packages'

    - script: |
        npm run ng build --configuration=production --optimization
      workingDirectory: $(Build.SourcesDirectory)/$(buildFrontEnd)
      displayName: '1.2.4. Build: Create Production Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/$(buildFrontEnd)/$(buildFrontEndDist)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(buildFrontEnd)/$(buildFrontEnd).zip'
        verbose: true
      displayName: '1.2.5. Publish: Create Archive Package in Staging Directory'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(buildFrontEnd)'
        artifact: 'FrontEnd'
        publishLocation: 'pipeline'
      displayName: '1.2.6. Publish: Publish FrontEnd Build as a Pipeline Artifact'

- stage: 'deploy_capstone_test'
  displayName: '2. Deploy to Test Environment'
  dependsOn:
    - build_capstone
  variables:
    - group: test

  jobs:
    - deployment: deploy_capstone_test_backend
      displayName: '2.1. Deploy BackEnd to Test'
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'BackEnd'
                targetPath: '$(Pipeline.Workspace)/BackEnd'
              displayName: '2.1.1. Retrieve: Download BackEnd Pipeline Artifacts'

            - task: FileTransform@2
              inputs:
                folderPath: '$(Pipeline.Workspace)/BackEnd/*.zip'
                jsonTargetFiles: '**/appsettings.json'
              displayName: '2.1.2. Replace: Adjust Database Connection String'

            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'Azure-CapStone-[semester]' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                appType: 'webApp'
                appName: '$(deployBackEnd)'
                package: '$(Pipeline.Workspace)/BackEnd/*.zip'
                deploymentMethod: 'auto'
              displayName: '2.1.3. Deploy: Deploy Azure Web App for Windows'

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'Database'
                targetPath: '$(Pipeline.Workspace)/Database'
              displayName: '2.1.4. Retrieve: Download Database Pipeline Artifacts'

            - task: SqlAzureDacpacDeployment@1
              inputs:
                azureSubscription: 'Azure-CapStone-[semester]' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                AuthenticationType: 'connectionString'
                ConnectionString: '$(deployDatabase)'
                deployType: 'SqlTask'
                SqlFile: '$(Pipeline.Workspace)/Database/todo-db-script.sql'
              displayName: '2.1.5. Deploy: Update Database'

    - deployment: deploy_capstone_test_frontend
      displayName: '2.2. Deploy FrontEnd to Test'
      dependsOn: deploy_capstone_test_backend
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'FrontEnd'
                targetPath: '$(Pipeline.Workspace)/FrontEnd'
              displayName: '2.2.1. Retrieve: Download Pipeline Artifacts'

            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: '$(Pipeline.Workspace)/FrontEnd/*.zip'
                destinationFolder: '$(Pipeline.Workspace)/FrontEnd/dist'
              displayName: '2.2.2. Retrieve: Extract Artifacts'

            - task: replacetokens@3
              inputs:
                targetFiles: '$(Pipeline.Workspace)/FrontEnd/dist/**/main*.js'
                encoding: 'auto'
                writeBOM: true
                verbosity: 'detailed'
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '#{'
                tokenSuffix: '}#'
                useLegacyPattern: false
                enableTelemetry: true
              displayName: '2.2.3. Replace: Replace BackEnd URL'

            - task: ArchiveFiles@2
              inputs:
                rootFolderOrFile: '$(Pipeline.Workspace)/FrontEnd/dist'
                includeRootFolder: false
                archiveType: 'zip'
                archiveFile: '$(Pipeline.Workspace)/FrontEnd/FrontEnd-Updated.zip'
                verbose: true
              displayName: '2.2.4. Replace: Create Archive Package in Pipeline Directory'

            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'Azure-CapStone-[semester]' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                appType: 'webAppLinux'
                appName: '$(deployFrontEnd)'
                package: '$(Pipeline.Workspace)/FrontEnd/FrontEnd-Updated.zip' 
                deploymentMethod: 'auto'
              displayName: '2.2.5. Deploy: Deploy Azure Web App for Linux'

- stage: 'deploy_capstone_prod'
  displayName: '3. Deploy to Production Environment'
  dependsOn:
    - build_capstone
    - deploy_capstone_test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    - group: prod

  jobs:
    - deployment: deploy_capstone_prod_backend
      displayName: '3.1. Deploy BackEnd to Prod'
      environment: prod
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'BackEnd'
                targetPath: '$(Pipeline.Workspace)/BackEnd'
              displayName: '3.1.1. Retrieve: Download Pipeline Artifacts'

            - task: FileTransform@2
              inputs:
                folderPath: '$(Pipeline.Workspace)/BackEnd/*.zip'
                jsonTargetFiles: '**/appsettings.json'
              displayName: '3.1.2. Replace: Adjust Database Connection String'

            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'Azure-CapStone-[semester]' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                appType: 'webApp'
                appName: '$(deployBackEnd)'
                package: '$(Pipeline.Workspace)/BackEnd/*.zip'
                deploymentMethod: 'auto'
              displayName: '3.1.3. Deploy: Deploy Azure Web App for Windows'

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'Database'
                targetPath: '$(Pipeline.Workspace)/Database'
              displayName: '3.1.4. Retrieve: Download Database Pipeline Artifacts'

            - task: SqlAzureDacpacDeployment@1
              inputs:
                azureSubscription: 'Azure-CapStone-[semester]' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                AuthenticationType: 'connectionString'
                ConnectionString: '$(ConnectionStrings)'
                deployType: 'SqlTask'
                SqlFile: '$(Pipeline.Workspace)/Database/todo-db-script.sql'
              displayName: '3.1.5. Deploy: Update Database'

    - deployment: deploy_capstone_prod_frontend
      displayName: '3.2. Deploy FrontEnd to Prod'
      dependsOn: deploy_capstone_prod_backend
      environment: prod
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none

              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'FrontEnd'
                  targetPath: '$(Pipeline.Workspace)/FrontEnd'
                displayName: '3.2.1. Retrieve: Download Pipeline Artifacts'

              - task: ExtractFiles@1
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)/FrontEnd/*.zip'
                  destinationFolder: '$(Pipeline.Workspace)/FrontEnd/dist'
                displayName: '3.2.2. Retrieve: Extract Artifacts'

              - task: replacetokens@3
                inputs:
                  targetFiles: '$(Pipeline.Workspace)/FrontEnd/dist/**/main*.js'
                  encoding: 'auto'
                  writeBOM: true
                  verbosity: 'detailed'
                  actionOnMissing: 'warn'
                  keepToken: false
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'
                  useLegacyPattern: false
                  enableTelemetry: true
                displayName: '3.2.3. Replace: Replace BackEnd URL'

              - task: ArchiveFiles@2
                inputs:
                  rootFolderOrFile: '$(Pipeline.Workspace)/FrontEnd/dist'
                  includeRootFolder: false
                  archiveType: 'zip'
                  archiveFile: '$(Pipeline.Workspace)/FrontEnd/FrontEnd-Updated.zip'
                  verbose: true
                displayName: '3.2.4. Replace: Create Archive Package in Pipeline Directory'

              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'Azure-CapStone-[semester]' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                  appType: 'webAppLinux'
                  appName: '$(deployFrontEnd)'
                  package: '$(Pipeline.Workspace)/FrontEnd/FrontEnd-Updated.zip' 
                  deploymentMethod: 'auto'
                displayName: '3.2.5. Deploy: Deploy Azure Web App for Linux'
